Correccion comunCasoPrueba::prueba_normaliza
pasosdeJesus/Mt77 pull request #3
Opened 2020-08-02 16:28 UTC by dhasane

Se estaba utilizando la cadena "aB\xE1\xC1\xF1\xC9\xED\xF3\xFA\xFC"
para esta prueba, aunque al momento de comparar los strings, no
realizaba la convercion a los caracteres esperados.
Adicionalmente en uno de los asserts se estaba probando que la
funcion 'normaliza' eliminara los espacios repetidos, pero de lo
que he entendido, esto siempre se hace antes de ingresar la cadena.
Algo similar a lo anterior, 'normaliza' de momento no esta eliminando
ningun caracter, por lo que al ingresar ':', este seguira estando en
la cadena resultante.

2020-08-05 07:09 UTC, vtamara requested changes
Mantener la funcionalidad que había, ampliar pruebas para cubrir nuevos casos.

2020-08-05 07:09 UTC, vtamara commented on comunCasoPrueba.cpp
> +        // CPPUNIT_ASSERT(
No se deben quitar pruebas, se deben ampliar para cubrir los nuevos casos y arreglar fuentes para que lo anterior siga pasando.

2020-08-05 07:09 UTC, vtamara commented on comunCasoPrueba.cpp
> +        // CPPUNIT_ASSERT(normaliza("      ") == "");
Es mejor que las funciones sigan haciendo lo que hacian antes, pero ahora ampliando a UTF-8

2020-08-05 07:09 UTC, vtamara commented on comunCasoPrueba.cpp
> +        CPPUNIT_ASSERT(normaliza("titulo:nombre") == "TITULO:NOMBRE");
Inicialmente es mejor que se comporte, como se comportaba antes.

2020-08-05 19:43 UTC, dhasane commented
Ya hice los cambios para que funcione de la misma manera como funcionaba antes. El problema estaba en que ahora los caracteres que sean distintos a los que se esperan son ingresados sin modificarlos para no tener problemas con utf-8. Hice para que ignorara en caso de encontrar " " o ":".

2020-08-07 16:19 UTC, dhasane commented
No se está modificando el comportamiento de : . Antes de los cambios, la función 'normaliza' eliminaba todo lo que no fueran letras.

2020-08-07 17:09 UTC, vtamara commented
Tiene razón, gracias!

2020-08-07 17:09 UTC, merged